Metrics/LineLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
